spring:
  datasource:
    url: 'postgres://localhost:5432/hsplayer'
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PosgreSQLDialect    